---
title: "DWV Assignment 4"
format:
  html:
    embed-resources: true 
  docx: default
---

## Part One: Lines
```{r}

# Load ggplot2 for creating graphs
library(ggplot2)

# Load dplyr for working with and summarizing data
library(dplyr)

# Q1, Q2, Q3
# Create the plot
ggplot() +
  
  # Draw tje line and make it purple and dashed
  geom_abline(intercept = 3, slope = 4,
              color = "purple",
              linetype = "dashed") +
  annotate("text", x = 2, y = 15,
           label = "y = 4x + 3") +
  # Sets the x-axis from -20 to 20
  xlim(-20, 20) +
  
  # Set the y-axis from -20 to 20
  ylim(-20, 20) +
  # Adds a title and axis laabels
  labs(
    title = "Line: y = 4x + 3",
    x = "x",
    y = "y"
  )

```


## Part Two: Protected Lands

Question 1
```{r}
# Read the data 
data <- read.csv("~/Documents/PAI741/Problem Set Four/data/protected_lands.csv")


# Q1: Find mean, standard deviation and range of each variable:
# protected_lands, gdp_percap, tot_gdp_billions

# protected_lands
mean(data$protected_lands)
sd(data$protected_lands)
range(data$protected_lands)

# gdp_percap
mean(data$gdp_percap)
sd(data$gdp_percap)
range(data$gdp_percap)

# tot_gdp_billions
mean(data$tot_gdp_bilions)
sd(data$tot_gdp_bilions)
range(data$tot_gdp_bilions)


# Q2: Create scatterplot where protected_lands is on y,
# gdp_percap is on x. Include title and axis labels

plot(data$gdp_percap, data$protected_lands,
     main = "Protected Lands and GDP Per Capita",
     xlab = "GDP Per Capita",
     ylab = "Protected Lands",
     pch = 16)


# Q3: Create scatterplot where protected_lands is on y,
# tot_gdp_billions is on x. Include title and axis labels

plot(data$tot_gdp_bilions, data$protected_lands,
     main = "Protected Lands and Total GDP",
     xlab = "Total GDP (Billions)",
     ylab = "Protected Lands",
     pch = 16)


# Q4: Regress protected_lands on gdp_percap

model1 <- lm(protected_lands ~ gdp_percap, data = data)

summary(model1)


# Q5: Create scatterplot where protected_lands is on y,
# gdp_percap is on x and overlay with best fit line

plot(data$gdp_percap, data$protected_lands,
     main = "Protected Lands and GDP Per Capita",
     xlab = "GDP Per Capita",
     ylab = "Protected Lands",
     pch = 16)

abline(model1, col = "blue", lwd = 2)
 

# Q6: Regress protected_lands on tot_gdp_billions

model2 <- lm(protected_lands ~ tot_gdp_bilions, data = data)

summary(model2)

 
# Q7: Create scatterplot where protected_lands is on y,
# tot_gdp_billions is on x. Overlay plot with best fit line

plot(data$tot_gdp_bilions, data$protected_lands,
     main = "Protected Lands and Total GDP",
     xlab = "Total GDP (Billions)",
     ylab = "Protected Lands",
     pch = 16)

abline(model2, col = "red", lwd = 2)
```




